# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, Crypto, dataenc, haskeline, QuickCheck, transformers }:

cabal.mkDerivation (self: {
  pname = "pwdhash";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [ Crypto dataenc haskeline transformers ];
  testDepends = [ QuickCheck ];
  meta = {
    description = "Implementation of the pwdhash algorithm";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
